attrscore visualize
footprinthere/AttAttr-Cutoff pull request #7
Opened 2022-12-02 19:04 UTC by YH-CHO

./run_vis.sh {task_name} {GPU} {layer strategy}

2022-12-03 14:37 UTC, footprinthere requested changes

2022-12-03 14:37 UTC, footprinthere commented on attrscore_visualize.py
> +    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
CPU로도 작동하나요?

2022-12-03 14:37 UTC, footprinthere commented on attrscore_visualize.py
> +        token_type_ids=None,            # None for test; 실제로는 segment id 입력
2개 문장을 다루는 task에 대해서는 이 부분을 `None`으로 넣으면 안 될 것 같습니다. `None`으로 넣으면 기본값으로 `0`으로 채워진 배열을 사용하게 됩니다.

2022-12-03 14:37 UTC, footprinthere commented on attrscore_visualize.py
> +    example_token_ids = input_ids[(input_ids != 1).nonzero(as_tuple=True)]
`ModelInput.input_len` 쓰셔도 될 듯합니다.

2022-12-03 16:03 UTC, YH-CHO commented on attrscore_visualize.py
> +    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
attrscore_generator가 cuda로만 작동해서 cpu로 작동 안합니다. attrscore_generator의 set device와 똑같이 수정했습니다.

2022-12-03 16:04 UTC, YH-CHO commented on attrscore_visualize.py
> +    example_token_ids = input_ids[(input_ids != 1).nonzero(as_tuple=True)]
input_len을 사용하여 간결하게 수정하였습니다.

2022-12-03 16:39 UTC, YH-CHO commented on attrscore_visualize.py
> +        token_type_ids=None,            # None for test; 실제로는 segment id 입력
inputs에서 token_type_ids를 얻을 수 있나요?

2022-12-04 00:44 UTC, footprinthere commented on attrscore_visualize.py
> +        token_type_ids=None,            # None for test; 실제로는 segment id 입력
네... trainer.py 참고해보세요.

2022-12-04 09:40 UTC, closed without merging